# Generated by Django 4.2.3 on 2023-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
